import os


source_and_dependencies = {
    "include_paths" : [],
    "sources" : {}
}


for dir, _, files in os.walk("."):

    for file in files:

        filename, suffix = os.path.splitext(file)

        if suffix == ".h":
            inc_dir_abspath = os.path.abspath(dir)
            if inc_dir_abspath not in source_and_dependencies["include_paths"]:
                source_and_dependencies["include_paths"].append(inc_dir_abspath)
        elif suffix == ".c":
            if filename[:5] == "test_":
                if filename[5:] not in source_and_dependencies["sources"]:
                    source_and_dependencies["sources"][filename[5:]] = {"source_file_path" : None, "test_file_path" : None}
                source_and_dependencies["sources"][filename[5:]]["test_file_path"] = os.path.abspath(os.path.join(dir, file))
            else:
                if filename not in source_and_dependencies["sources"]:
                    source_and_dependencies["sources"][filename] = {"source_file_path" : None, "test_file_path" : None}
                source_and_dependencies["sources"][filename]["source_file_path"] = os.path.abspath(os.path.join(dir, file))


Return("source_and_dependencies")
