import os


source_and_dependencies = {
    "include_paths" : [],
    "sources" : {}
}


for dirpath, _, filenames in os.walk("."):

    for filename in filenames:

        dir = Dir(os.path.abspath(dirpath))
        file = File(filename, dir)

        if file.suffix == ".h":
        
            if dir.abspath not in source_and_dependencies["include_paths"]:
                source_and_dependencies["include_paths"].append(dir.abspath)
        
        elif file.suffix == ".c":
        
            basename = file.name.replace(file.suffix, "")

            if basename[:5] == "test_":
                if basename[5:] not in source_and_dependencies["sources"]:
                    source_and_dependencies["sources"][basename[5:]] = {"source_file" : None, "test_file" : None}
                source_and_dependencies["sources"][basename[5:]]["test_file"] = file
            else:
                if basename not in source_and_dependencies["sources"]:
                    source_and_dependencies["sources"][basename] = {"source_file" : None, "test_file" : None}
                source_and_dependencies["sources"][basename]["source_file"] = file


Return("source_and_dependencies")
